AWSTemplateFormatVersion: "2010-09-09"
Description: Lacework AWS Config Security Audit Integration

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Parameters:
          - ResourceNamePrefix
          - ExternalID
          - LaceworkAccount
          - MainAccountSNS
    ParameterLabels:
      ResourceNamePrefix:
        default: Resource name prefix
      ExternalID:
        default: ExternalID
      LaceworkAccount:
        default: Lacework Account (do not include '.lacework.net')
      MainAccountSNS:
        default: SNS Topic in main account

Parameters:
  ResourceNamePrefix:
    Default: lw-prefix
    Description: Names of resources created by the stack will be prefixed with this value to ensure uniqueness.
    Type: String
    MinLength: "1"
    MaxLength: "45"
    AllowedPattern: ^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$
    ConstraintDescription: Invalid resource name prefix.  Must match pattern ^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$
  ExternalID:
    Description: >-
      The cross-account access role created by the stack will use this value in
      the ExternalID.
    Type: String
    MinLength: '10'
    MaxLength: '10'
    AllowedPattern: ^[a-zA-Z0-9=,.@:/-]{10}$
    ConstraintDescription: >-
      Invalid ExternalID value.  Must match pattern
      ^[a-zA-Z0-9=,.@:/-]{10}$.  Must be 10 characters long.
  LaceworkAccount:
    Type: String
    Description: "Enter your Lacework account name. Do not include the '.lacework.net' at the end."
    MinLength: '1'
  MainAccountSNS:
    Description: ARN of SNS topic that we post to start the integration
    Type: String

Resources:
  LaceworkCrossAccountAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Join:
          - '-'
          - - Ref: ResourceNamePrefix
            - laceworkcwsrole-sa
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - 'arn:aws:iam::'
                    - "434813966438"
                    - :root
            Condition:
              StringEquals:
                sts:ExternalId: !Sub [ 'lweid:aws:v2:${LaceworkAccount}:${AWS::AccountId}:${ExternalID}', { LaceworkAccount: !Ref LaceworkAccount, ExternalID: !Ref ExternalID } ]
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit

  LaceworkCWSPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: LaceworkCWSPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: GetEc2DefaultEncryption
            Action:
              - ec2:GetEbsEncryptionByDefault
            Effect: Allow
            Resource: '*'
          - Sid: GetBucketPublicAccessBlock
            Action:
              - s3:GetBucketPublicAccessBlock
            Effect: Allow
            Resource: '*'
      Roles:
        - Ref: LaceworkCrossAccountAccessRole

  LaceworkSnsCustomResource:
    Type: Custom::LaceworkSnsCustomResource
    DependsOn:
      - LaceworkCWSPolicy
      - LaceworkCrossAccountAccessRole
    Properties:
      Type: AWS_CFG
      ServiceToken: !Ref MainAccountSNS
      RoleArn:
        Fn::GetAtt:
          - LaceworkCrossAccountAccessRole
          - Arn
      ExternalId: !Sub [ 'lweid:aws:v2:${LaceworkAccount}:${AWS::AccountId}:${ExternalID}', { LaceworkAccount: !Ref LaceworkAccount, ExternalID: !Ref ExternalID } ]
      AccountId:
        Ref: AWS::AccountId

Outputs:
  ExternalID:
    Description: External ID to share with Lacework AWS Config Security Audit
    Value: !Sub [ 'lweid:aws:v2:${LaceworkAccount}:${AWS::AccountId}:${ExternalID}', { LaceworkAccount: !Ref LaceworkAccount, ExternalID: !Ref ExternalID } ]
  RoleARN:
    Description: Cross account Role ARN for Lacework AWS Config Security Audit
    Value:
      Fn::GetAtt:
        - LaceworkCrossAccountAccessRole
        - Arn
  TemplateVersion:
    Description: Template version
    Value: "1.0"
